import type { Product, Order, User } from '../types'

export const demoSeller: User = {
  id: 'seller-1',
  email: 'marco@italianfashion.it',
  full_name: 'Marco Rossini',
  role: 'seller',
  whatsapp: '393331234567',
  company: 'Rossini Tessuti Milano',
  verified: true,
  created_at: '2024-01-01T00:00:00Z',
}

export const demoBuyer: User = {
  id: 'buyer-1',
  email: 'wang@fashionbiz.nl',
  full_name: '王 丽华',
  role: 'buyer',
  whatsapp: '31612345678',
  company: 'Wang Fashion Amsterdam',
  verified: true,
  created_at: '2024-01-01T00:00:00Z',
}

export const demoAdmin: User = {
  id: 'admin-1',
  email: 'admin@pocketmoda.com',
  full_name: 'Admin',
  role: 'admin',
  verified: true,
  created_at: '2024-01-01T00:00:00Z',
}

export const demoProducts: Product[] = [
  {
    id: 'p1',
    seller_id: 'seller-1',
    seller: demoSeller,
    title: 'Silk Blouse Primavera',
    brand: 'Rossini',
    description: '100% pure silk blouse from Milan. Lightweight, elegant drape. Perfect for spring/summer collections.',
    fabric: 'Silk',
    region: 'Milan',
    moq: 10,
    tier_prices: [
      { min_qty: 10, max_qty: 49, price_eur: 45 },
      { min_qty: 50, max_qty: 99, price_eur: 38 },
      { min_qty: 100, max_qty: null, price_eur: 30 },
    ],
    is_pronto: true,
    stock_qty: 240,
    images: [
      'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=600&q=80',
      'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=600&q=80',
    ],
    is_active: true,
    created_at: '2024-01-10T00:00:00Z',
  },
  {
    id: 'p2',
    seller_id: 'seller-1',
    seller: demoSeller,
    title: 'Cashmere Turtleneck Invernale',
    brand: 'Rossini',
    description: 'Grade A cashmere turtleneck from Tuscany. Ultra-soft, preshrunk. Available in 8 colours.',
    fabric: 'Cashmere',
    region: 'Tuscany',
    moq: 5,
    tier_prices: [
      { min_qty: 5, max_qty: 19, price_eur: 120 },
      { min_qty: 20, max_qty: 49, price_eur: 98 },
      { min_qty: 50, max_qty: null, price_eur: 80 },
    ],
    is_pronto: false,
    stock_qty: 0,
    images: [
      'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&q=80',
    ],
    is_active: true,
    created_at: '2024-01-12T00:00:00Z',
  },
  {
    id: 'p3',
    seller_id: 'seller-1',
    seller: demoSeller,
    title: 'Linen Summer Blazer',
    brand: 'Venezia Moda',
    description: 'Pure linen blazer from Veneto. Unstructured, breathable. Italian craftsmanship.',
    fabric: 'Linen',
    region: 'Veneto',
    moq: 8,
    tier_prices: [
      { min_qty: 8, max_qty: 29, price_eur: 85 },
      { min_qty: 30, max_qty: null, price_eur: 68 },
    ],
    is_pronto: true,
    stock_qty: 96,
    images: [
      'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&q=80',
    ],
    is_active: true,
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'p4',
    seller_id: 'seller-1',
    seller: demoSeller,
    title: 'Wool Coat Classico',
    brand: 'Fiorentino',
    description: 'Double-face wool coat from Florence. Timeless cut, season-proof fabric.',
    fabric: 'Wool',
    region: 'Florence',
    moq: 6,
    tier_prices: [
      { min_qty: 6, max_qty: 19, price_eur: 210 },
      { min_qty: 20, max_qty: null, price_eur: 175 },
    ],
    is_pronto: false,
    stock_qty: 0,
    images: [
      'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=600&q=80',
    ],
    is_active: true,
    created_at: '2024-01-18T00:00:00Z',
  },
  {
    id: 'p5',
    seller_id: 'seller-1',
    seller: demoSeller,
    title: 'Leather Mini Skirt',
    brand: 'Napoli Couture',
    description: 'Genuine Italian leather mini skirt, hand-stitched edges. Sizes XS–XL.',
    fabric: 'Leather',
    region: 'Naples',
    moq: 10,
    tier_prices: [
      { min_qty: 10, max_qty: 29, price_eur: 95 },
      { min_qty: 30, max_qty: null, price_eur: 75 },
    ],
    is_pronto: true,
    stock_qty: 60,
    images: [
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&q=80',
    ],
    is_active: true,
    created_at: '2024-01-20T00:00:00Z',
  },
  {
    id: 'p6',
    seller_id: 'seller-1',
    seller: demoSeller,
    title: 'Denim Jacket Artigianale',
    brand: 'Venezia Moda',
    description: 'Stone-washed denim jacket with artisan detailing. Made in Veneto.',
    fabric: 'Denim',
    region: 'Veneto',
    moq: 12,
    tier_prices: [
      { min_qty: 12, max_qty: 49, price_eur: 55 },
      { min_qty: 50, max_qty: null, price_eur: 42 },
    ],
    is_pronto: true,
    stock_qty: 144,
    images: [
      'https://images.unsplash.com/photo-1551854839-8ba7db3e3535?w=600&q=80',
    ],
    is_active: true,
    created_at: '2024-01-22T00:00:00Z',
  },
]

export const demoOrders: Order[] = [
  {
    id: 'ord-001',
    buyer_id: 'buyer-1',
    buyer: demoBuyer,
    seller_id: 'seller-1',
    seller: demoSeller,
    order_type: 'pronto',
    status: 'confirmed',
    items: [
      {
        product_id: 'p1',
        product: demoProducts[0],
        quantity: 20,
        unit_price: 38,
        total: 760,
      },
    ],
    notes: 'Please ship to Amsterdam warehouse.',
    total_eur: 760,
    created_at: '2024-02-01T10:00:00Z',
    updated_at: '2024-02-01T11:00:00Z',
  },
  {
    id: 'ord-002',
    buyer_id: 'buyer-1',
    buyer: demoBuyer,
    seller_id: 'seller-1',
    seller: demoSeller,
    order_type: 'pre_order',
    status: 'in_production',
    items: [
      {
        product_id: 'p2',
        product: demoProducts[1],
        quantity: 30,
        unit_price: 98,
        total: 2940,
      },
    ],
    total_eur: 2940,
    created_at: '2024-02-05T09:00:00Z',
    updated_at: '2024-02-06T14:00:00Z',
  },
  {
    id: 'ord-003',
    buyer_id: 'buyer-1',
    buyer: demoBuyer,
    seller_id: 'seller-1',
    seller: demoSeller,
    order_type: 'pronto',
    status: 'pending',
    items: [
      {
        product_id: 'p3',
        product: demoProducts[2],
        quantity: 15,
        unit_price: 85,
        total: 1275,
      },
    ],
    total_eur: 1275,
    created_at: '2024-02-10T16:00:00Z',
    updated_at: '2024-02-10T16:00:00Z',
  },
]
